export const nationalities = [
  { name: "Albania", code: "AL", accentColor: "#E41E20" },
  { name: "Argentina", code: "AR", accentColor: "#74ACDF" },
  { name: "Armenia", code: "AM", accentColor: "#D90012" },
  { name: "Australia", code: "AU", accentColor: "#002868" },
  { name: "Austria", code: "AT", accentColor: "#ED2939" },
  { name: "Azerbaijan", code: "AZ", accentColor: "#0092BC" },
  { name: "Bahrain", code: "BH", accentColor: "#D71A28" },
  { name: "Belarus", code: "BY", accentColor: "#CF101A" },
  { name: "Belgium", code: "BE", accentColor: "#000000" },
  { name: "Bolivia", code: "BO", accentColor: "#D52B1E" },
  { name: "Bosnia and Herzegovina", code: "BA", accentColor: "#002395" },
  { name: "Brazil", code: "BR", accentColor: "#009739" },
  { name: "Bulgaria", code: "BG", accentColor: "#00966E" },
  { name: "Canada", code: "CA", accentColor: "#FF0000" },
  { name: "Chile", code: "CL", accentColor: "#D52B1E" },
  { name: "China", code: "CN", accentColor: "#DE2910" },
  { name: "Colombia", code: "CO", accentColor: "#FCD116" },
  { name: "Croatia", code: "HR", accentColor: "#FF0000" },
  { name: "Cyprus", code: "CY", accentColor: "#007A3D" },
  { name: "Czechia", code: "CZ", accentColor: "#11457E" },
  { name: "Denmark", code: "DK", accentColor: "#C60C30" },
  { name: "Ecuador", code: "EC", accentColor: "#FFD100" },
  { name: "Estonia", code: "EE", accentColor: "#0072CE" },
  { name: "Finland", code: "FI", accentColor: "#003580" },
  { name: "France", code: "FR", accentColor: "#0055A4" },
  { name: "Georgia", code: "GE", accentColor: "#FF0000" },
  { name: "Germany", code: "DE", accentColor: "#000000" },
  { name: "Greece", code: "GR", accentColor: "#0D5EAF" },
  { name: "Hungary", code: "HU", accentColor: "#436F4D" },
  { name: "Iceland", code: "IS", accentColor: "#003897" },
  { name: "India", code: "IN", accentColor: "#FF9933" },
  { name: "Iraq", code: "IQ", accentColor: "#CE1126" },
  { name: "Ireland", code: "IE", accentColor: "#169B62" },
  { name: "Italy", code: "IT", accentColor: "#009246" },
  { name: "Japan", code: "JP", accentColor: "#BC002D" },
  { name: "Kuwait", code: "KW", accentColor: "#007847" },
  { name: "Latvia", code: "LV", accentColor: "#9E3039" },
  { name: "Lithuania", code: "LT", accentColor: "#FDB913" },
  { name: "Luxembourg", code: "LU", accentColor: "#00A1DE" },
  { name: "North Macedonia", code: "MK", accentColor: "#CE2028" },
  { name: "Malaysia", code: "MY", accentColor: "#010066" },
  { name: "Malta", code: "MT", accentColor: "#C60B1E" },
  { name: "Mexico", code: "MX", accentColor: "#006847" },
  { name: "Moldova", code: "MD", accentColor: "#003DA5" },
  { name: "Monaco", code: "MC", accentColor: "#CE1126" },
  { name: "Montenegro", code: "ME", accentColor: "#D4AF37" },
  { name: "Netherlands", code: "NL", accentColor: "#21468B" },
  { name: "New Zealand", code: "NZ", accentColor: "#00247D" },
  { name: "Norway", code: "NO", accentColor: "#BA0C2F" },
  { name: "Oman", code: "OM", accentColor: "#D71A28" },
  { name: "Paraguay", code: "PY", accentColor: "#002B7F" },
  { name: "Peru", code: "PE", accentColor: "#D91023" },
  { name: "Poland", code: "PL", accentColor: "#DC143C" },
  { name: "Portugal", code: "PT", accentColor: "#006600" },
  { name: "Qatar", code: "QA", accentColor: "#8D1B3D" },
  { name: "Republic of Kosovo", code: "XK", accentColor: "#2434AA" },
  { name: "Romania", code: "RO", accentColor: "#002B7F" },
  { name: "Russia", code: "RU", accentColor: "#D52B1E" },
  { name: "San Marino", code: "SM", accentColor: "#007FFF" },
  { name: "Saudi Arabia", code: "SA", accentColor: "#006C35" },
  { name: "Serbia", code: "RS", accentColor: "#C6363C" },
  { name: "Singapore", code: "SG", accentColor: "#ED2939" },
  { name: "Slovakia", code: "SK", accentColor: "#0B4EA2" },
  { name: "Slovenia", code: "SI", accentColor: "#005BBB" },
  { name: "South Africa", code: "ZA", accentColor: "#007A4D" },
  { name: "South Korea", code: "KR", accentColor: "#C60C30" },
  { name: "Spain", code: "ES", accentColor: "#AA151B" },
  { name: "Sweden", code: "SE", accentColor: "#005CBF" },
  { name: "Switzerland", code: "CH", accentColor: "#FF0000" },
  { name: "Taiwan*", code: "TW", accentColor: "#FE0000" },
  { name: "Ukraine", code: "UA", accentColor: "#005BBB" },
  { name: "United Arab Emirates", code: "AE", accentColor: "#00732F" },
  { name: "United Kingdom", code: "GB", accentColor: "#012169" },
  { name: "Scotland", code: "GB-SCT", accentColor: "#005EB8" },
  { name: "Wales", code: "GB-WLS", accentColor: "#D30731" },
  { name: "United States", code: "US", accentColor: "#B22234" },
  { name: "Uruguay", code: "UY", accentColor: "#00AEEF" },
  { name: "Vatican City", code: "VA", accentColor: "#FFD700" },
  { name: "Venezuela", code: "VE", accentColor: "#CF142B" }
];

export const allNationalities = [
  { name: "Afghanistan", code: "AF", accentColor: "#000000" },
  { name: "Albania", code: "AL", accentColor: "#E41E20" },
  { name: "Algeria", code: "DZ", accentColor: "#006233" },
  { name: "Andorra", code: "AD", accentColor: "#002E5D" },
  { name: "Angola", code: "AO", accentColor: "#CC0000" },
  { name: "Antigua and Barbuda", code: "AG", accentColor: "#EF3340" },
  { name: "Argentina", code: "AR", accentColor: "#74ACDF" },
  { name: "Armenia", code: "AM", accentColor: "#D90012" },
  { name: "Australia", code: "AU", accentColor: "#002868" },
  { name: "Austria", code: "AT", accentColor: "#ED2939" },
  { name: "Azerbaijan", code: "AZ", accentColor: "#0092BC" },
  { name: "The Bahamas", code: "BS", accentColor: "#00A3E0" },
  { name: "Bahrain", code: "BH", accentColor: "#D71A28" },
  { name: "Bangladesh", code: "BD", accentColor: "#006A4E" },
  { name: "Barbados", code: "BB", accentColor: "#00A1DE" },
  { name: "Belarus", code: "BY", accentColor: "#CF101A" },
  { name: "Belgium", code: "BE", accentColor: "#000000" },
  { name: "Belize", code: "BZ", accentColor: "#003893" },
  { name: "Benin", code: "BJ", accentColor: "#008751" },
  { name: "Bhutan", code: "BT", accentColor: "#FF8000" },
  { name: "Bolivia", code: "BO", accentColor: "#D52B1E" },
  { name: "Bosnia and Herzegovina", code: "BA", accentColor: "#002395" },
  { name: "Botswana", code: "BW", accentColor: "#00A3E0" },
  { name: "Brazil", code: "BR", accentColor: "#009739" },
  { name: "Brunei", code: "BN", accentColor: "#FFD100" },
  { name: "Bulgaria", code: "BG", accentColor: "#00966E" },
  { name: "Burkina Faso", code: "BF", accentColor: "#EF2B2D" },
  { name: "Burundi", code: "BI", accentColor: "#CE1126" },
  { name: "Cabo Verde", code: "CV", accentColor: "#003893" },
  { name: "Cambodia", code: "KH", accentColor: "#032EA1" },
  { name: "Cameroon", code: "CM", accentColor: "#007A5E" },
  { name: "Canada", code: "CA", accentColor: "#FF0000" },
  { name: "Central African Republic", code: "CF", accentColor: "#289728" },
  { name: "Chad", code: "TD", accentColor: "#002664" },
  { name: "Chile", code: "CL", accentColor: "#D52B1E" },
  { name: "China", code: "CN", accentColor: "#DE2910" },
  { name: "Colombia", code: "CO", accentColor: "#FCD116" },
  { name: "Comoros", code: "KM", accentColor: "#3A75C4" },
  { name: "Democratic Republic of the Congo", code: "CD", accentColor: "#007FFF" },
  { name: "Republic of the Congo", code: "CG", accentColor: "#009A44" },
  { name: "Costa Rica", code: "CR", accentColor: "#002B7F" },
  { name: "Croatia", code: "HR", accentColor: "#FF0000" },
  { name: "Cuba", code: "CU", accentColor: "#002A8F" },
  { name: "Cyprus", code: "CY", accentColor: "#007A3D" },
  { name: "Czechia", code: "CZ", accentColor: "#11457E" },
  { name: "Denmark", code: "DK", accentColor: "#C60C30" },
  { name: "Djibouti", code: "DJ", accentColor: "#6AB2E7" },
  { name: "Dominica", code: "DM", accentColor: "#006B3F" },
  { name: "Dominican Republic", code: "DO", accentColor: "#002D62" },
  { name: "Ecuador", code: "EC", accentColor: "#FFD100" },
  { name: "Egypt", code: "EG", accentColor: "#C8102E" },
  { name: "El Salvador", code: "SV", accentColor: "#0F47AF" },
  { name: "Equatorial Guinea", code: "GQ", accentColor: "#3E9A00" },
  { name: "Eritrea", code: "ER", accentColor: "#4189DD" },
  { name: "Estonia", code: "EE", accentColor: "#0072CE" },
  { name: "Eswatini", code: "SZ", accentColor: "#3E5EB9" },
  { name: "Ethiopia", code: "ET", accentColor: "#078930" },
  { name: "Federated States of Micronesia", code: "FM", accentColor: "#0033A0" },
  { name: "Fiji", code: "FJ", accentColor: "#68BFE5" },
  { name: "Finland", code: "FI", accentColor: "#003580" },
  { name: "France", code: "FR", accentColor: "#0055A4" },
  { name: "Gabon", code: "GA", accentColor: "#009E60" },
  { name: "The Gambia", code: "GM", accentColor: "#3A7728" },
  { name: "Georgia", code: "GE", accentColor: "#FF0000" },
  { name: "Germany", code: "DE", accentColor: "#000000" },
  { name: "Ghana", code: "GH", accentColor: "#006B3F" },
  { name: "Greece", code: "GR", accentColor: "#0D5EAF" },
  { name: "Grenada", code: "GD", accentColor: "#007847" },
  { name: "Guatemala", code: "GT", accentColor: "#0073CF" },
  { name: "Guinea", code: "GN", accentColor: "#CE1126" },
  { name: "Guinea-Bissau", code: "GW", accentColor: "#CE1126" },
  { name: "Guyana", code: "GY", accentColor: "#009739" },
  { name: "Haiti", code: "HT", accentColor: "#00209F" },
  { name: "Honduras", code: "HN", accentColor: "#0073CF" },
  { name: "Hong Kong Special Administrative Region", code: "HK", accentColor: "#DE2910" },
  { name: "Hungary", code: "HU", accentColor: "#436F4D" },
  { name: "Iceland", code: "IS", accentColor: "#003897" },
  { name: "India", code: "IN", accentColor: "#FF9933" },
  { name: "Indonesia", code: "ID", accentColor: "#CE1126" },
  { name: "Iran", code: "IR", accentColor: "#239F40" },
  { name: "Iraq", code: "IQ", accentColor: "#CE1126" },
  { name: "Ireland", code: "IE", accentColor: "#169B62" },
  { name: "Israel", code: "IL", accentColor: "#0038B8" },
  { name: "Italy", code: "IT", accentColor: "#009246" },
  { name: "Ivory Coast", code: "CI", accentColor: "#F77F00" },
  { name: "Jamaica", code: "JM", accentColor: "#000000" },
  { name: "Japan", code: "JP", accentColor: "#BC002D" },
  { name: "Jordan", code: "JO", accentColor: "#007A3D" },
  { name: "Kazakhstan", code: "KZ", accentColor: "#00AFCA" },
  { name: "Kenya", code: "KE", accentColor: "#006600" },
  { name: "Kiribati", code: "KI", accentColor: "#E21B23" },
  { name: "Kuwait", code: "KW", accentColor: "#007847" },
  { name: "Kyrgyzstan", code: "KG", accentColor: "#E8112D" },
  { name: "Laos", code: "LA", accentColor: "#CE1126" },
  { name: "Latvia", code: "LV", accentColor: "#9E3039" },
  { name: "Lebanon", code: "LB", accentColor: "#00A651" },
  { name: "Lesotho", code: "LS", accentColor: "#009A44" },
  { name: "Liberia", code: "LR", accentColor: "#BF0A30" },
  { name: "Libya", code: "LY", accentColor: "#000000" },
  { name: "Liechtenstein", code: "LI", accentColor: "#002868" },
  { name: "Lithuania", code: "LT", accentColor: "#FDB913" },
  { name: "Luxembourg", code: "LU", accentColor: "#00A1DE" },
  { name: "Macao Special Administrative Region", code: "MO", accentColor: "#007A5E" },
  { name: "Madagascar", code: "MG", accentColor: "#FC3D32" },
  { name: "Malawi", code: "MW", accentColor: "#000000" },
  { name: "Malaysia", code: "MY", accentColor: "#010066" },
  { name: "Maldives", code: "MV", accentColor: "#D21034" },
  { name: "Mali", code: "ML", accentColor: "#009A00" },
  { name: "Malta", code: "MT", accentColor: "#C60B1E" },
  { name: "Marshall Islands", code: "MH", accentColor: "#005BBB" },
  { name: "Mauritania", code: "MR", accentColor: "#006233" },
  { name: "Mauritius", code: "MU", accentColor: "#F75236" },
  { name: "Mexico", code: "MX", accentColor: "#006847" },
  { name: "Moldova", code: "MD", accentColor: "#003DA5" },
  { name: "Monaco", code: "MC", accentColor: "#CE1126" },
  { name: "Mongolia", code: "MN", accentColor: "#C4272F" },
  { name: "Montenegro", code: "ME", accentColor: "#D4AF37" },
  { name: "Morocco", code: "MA", accentColor: "#C1272D" },
  { name: "Mozambique", code: "MZ", accentColor: "#009A44" },
  { name: "Myanmar", code: "MM", accentColor: "#FECB00" },
  { name: "Namibia", code: "NA", accentColor: "#003580" },
  { name: "Nauru", code: "NR", accentColor: "#0072CE" },
  { name: "Nepal", code: "NP", accentColor: "#003893" },
  { name: "Netherlands", code: "NL", accentColor: "#21468B" },
  { name: "New Zealand", code: "NZ", accentColor: "#00247D" },
  { name: "Nicaragua", code: "NI", accentColor: "#002B7F" },
  { name: "Niger", code: "NE", accentColor: "#E05206" },
  { name: "Nigeria", code: "NG", accentColor: "#008751" },
  { name: "North Korea", code: "KP", accentColor: "#024FA2" },
  { name: "North Macedonia", code: "MK", accentColor: "#CE2028" },
  { name: "Norway", code: "NO", accentColor: "#BA0C2F" },
  { name: "Oman", code: "OM", accentColor: "#D71A28" },
  { name: "Pakistan", code: "PK", accentColor: "#01411C" },
  { name: "Palau", code: "PW", accentColor: "#003897" },
  { name: "Palestine", code: "PS", accentColor: "#000000" },
  { name: "Panama", code: "PA", accentColor: "#007AB8" },
  { name: "Papua New Guinea", code: "PG", accentColor: "#FF0000" },
  { name: "Paraguay", code: "PY", accentColor: "#002B7F" },
  { name: "Peru", code: "PE", accentColor: "#D91023" },
  { name: "Philippines", code: "PH", accentColor: "#0038A8" },
  { name: "Poland", code: "PL", accentColor: "#DC143C" },
  { name: "Portugal", code: "PT", accentColor: "#006600" },
  { name: "Qatar", code: "QA", accentColor: "#8D1B3D" },
  { name: "Romania", code: "RO", accentColor: "#002B7F" },
  { name: "Russia", code: "RU", accentColor: "#D52B1E" },
  { name: "Rwanda", code: "RW", accentColor: "#20603D" },
  { name: "St Kitts and Nevis", code: "KN", accentColor: "#007847" },
  { name: "St Lucia", code: "LC", accentColor: "#009EDE" },
  { name: "St Vincent and the Grenadines", code: "VC", accentColor: "#FFD100" },
  { name: "Samoa", code: "WS", accentColor: "#002B7F" },
  { name: "San Marino", code: "SM", accentColor: "#007FFF" },
  { name: "São Tomé and Príncipe", code: "ST", accentColor: "#12AD2B" },
  { name: "Saudi Arabia", code: "SA", accentColor: "#006C35" },
  { name: "Senegal", code: "SN", accentColor: "#00853F" },
  { name: "Serbia", code: "RS", accentColor: "#C6363C" },
  { name: "Seychelles", code: "SC", accentColor: "#003C71" },
  { name: "Sierra Leone", code: "SL", accentColor: "#1EB53A" },
  { name: "Singapore", code: "SG", accentColor: "#ED2939" },
  { name: "Slovakia", code: "SK", accentColor: "#0B4EA2" },
  { name: "Slovenia", code: "SI", accentColor: "#005BBB" },
  { name: "Solomon Islands", code: "SB", accentColor: "#0072CE" },
  { name: "Somalia", code: "SO", accentColor: "#4189DD" },
  { name: "South Africa", code: "ZA", accentColor: "#007A4D" },
  { name: "South Korea", code: "KR", accentColor: "#C60C30" },
  { name: "South Sudan", code: "SS", accentColor: "#078930" },
  { name: "Spain", code: "ES", accentColor: "#AA151B" },
  { name: "Sri Lanka", code: "LK", accentColor: "#8D153A" },
  { name: "Sudan", code: "SD", accentColor: "#D21034" },
  { name: "Suriname", code: "SR", accentColor: "#377E3F" },
  { name: "Sweden", code: "SE", accentColor: "#005CBF" },
  { name: "Switzerland", code: "CH", accentColor: "#FF0000" },
  { name: "Syria", code: "SY", accentColor: "#CE1126" },
  { name: "Taiwan*", code: "TW", accentColor: "#FE0000" },
  { name: "Tajikistan", code: "TJ", accentColor: "#CC0000" },
  { name: "Tanzania", code: "TZ", accentColor: "#1EB53A" },
  { name: "Thailand", code: "TH", accentColor: "#A51931" },
  { name: "Timor-Leste", code: "TL", accentColor: "#DC241F" },
  { name: "Togo", code: "TG", accentColor: "#006A4E" },
  { name: "Tonga", code: "TO", accentColor: "#C8102E" },
  { name: "Trinidad and Tobago", code: "TT", accentColor: "#CE1126" },
  { name: "Tunisia", code: "TN", accentColor: "#E70013" },
  { name: "Turkey", code: "TR", accentColor: "#E30A17" },
  { name: "Turkmenistan", code: "TM", accentColor: "#31A84C" },
  { name: "Tuvalu", code: "TV", accentColor: "#1D7FC1" },
  { name: "Uganda", code: "UG", accentColor: "#000000" },
  { name: "Ukraine", code: "UA", accentColor: "#005BBB" },
  { name: "United Arab Emirates", code: "AE", accentColor: "#00732F" },
  { name: "United Kingdom", code: "GB", accentColor: "#012169" },
  { name: "United States", code: "US", accentColor: "#B22234" },
  { name: "Uruguay", code: "UY", accentColor: "#00AEEF" },
  { name: "Uzbekistan", code: "UZ", accentColor: "#1EB53A" },
  { name: "Vanuatu", code: "VU", accentColor: "#009543" },
  { name: "Vatican City", code: "VA", accentColor: "#FFD700" },
  { name: "Venezuela", code: "VE", accentColor: "#CF142B" },
  { name: "Vietnam", code: "VN", accentColor: "#DA251D" },
  { name: "Yemen", code: "YE", accentColor: "#CE1126" },
  { name: "Zambia", code: "ZM", accentColor: "#198A00" },
  { name: "Zimbabwe", code: "ZW", accentColor: "#006400" },
];
